#!/bin/sh

if [[ $(uname -s) == "Darwin" ]]; then
    alias copy="pbcopy"
    alias paste="pbpaste"

	alias tunnel="sshuttle --dns -r home 0/0 -vv"
    alias remove-dsstore="find . -name '*.DS_Store' -type f -delete"

    alias chrome="open -a 'Google Chrome'"
    alias safari="open -a 'Safari'"
fi
